name: 'Line Message Notify'
description: 'Sending a Line message'
author: 'Bo-Yi Wu'
inputs:
  secret:
    description: 'line channel secret'
    required: true
  token:
    description: 'line channel access token'
    required: true
  room:
    description: 'line room ID'
  group:
    description: 'line group ID'
  message:
    description: 'the message contents'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-square'
  color: 'gray-dark'
