name: line message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send location message
      uses: actions/checkout@master
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        message: "xxx"
