name: line message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send location message
      uses: actions/checkout@master
      with:
        secret: ${{ secrets.secret }}
        token: ${{ secrets.GITHUB_TOKEN }}
        room: ${{ secrets.room }}
        locations: "竹北體育館::新竹縣竹北市::24.834687::120.993368"
